# frozen_string_literal: true

namespace :resources do
  desc "Resource Creation"

  task :create_resources => [ :environment ] do
    Resource.create([
      { name: "Headspace", image: "headspace", about: "Guided meditations, sleep aids, and movement exercises ", details: "Free app available for Android and Apple, offering FREE access to a selection of meditations called “Weathering the Storm”", link: "https://www.headspace.com/covid-19", link_text: "https://www.headspace.com/covid-19", notes: "This includes a “Beginners Meditation” series that teaches you how to meditate!", category: "depressed_lonely_anxious", published: true },
      { name: "HealthyMinds", image: "healthy_minds", about: "Guided mindfulness and meditation podcasts with ability to measure and track your emotional well-being", details: "Free app available for Android and Apple, all content is FREE for individual users", link: "https://tryhealthyminds.org/", link_text: "https://tryhealthyminds.org/", notes: "This mindfulness app was developed by neuroscientists!", category: "depressed_lonely_anxious", published: true },
      { name: "Get Moving", image: "healthy_minds", about: "Science shows that movement is good for mental health. Whether you are going for a walk outside or dancing in your living room, movement promotes emotional well-being.", details: "Go for a walk or run, play with your dog outside, go for a bike ride, or do an online dance class or yoga flow.", notes: "However you like to move, there is a way to do it while socially distancing.", category: "depressed_lonely_anxious", published: true },
      { name: "Stay-at-Home Self-Care Coloring Book", image: "self_care_coloring", about: "A downloadable coloring book from the blogger @selfcareisforeveryone that includes ideas of how to promote self-care while at home", details: "You can print the PDF below and color to your heart’s content.", link: "https://drive.google.com/file/d/167mu47LGnW4kHNW9sVEDZ9wC5otyCcyb/view?usp=sharing", link_text: "Click this link to access the coloring book", notes: "Coloring can be a simple activity to distract yourself and promote mindfulness", category: "depressed_lonely_anxious", published: true },
      { name: "Strategies to Reduce Stress and Anxiety ", image: "reduce_stress_strategies", about: "Website pages that offer strategies on reducing anxiety caused by the current COVID-19 pandemic", details: "Read through these easy-to-read resources and try some of these tips", link: "https://www.cdc.gov/coronavirus/2019-ncov/daily-life-coping/managing-stress-anxiety.html?CDC_AA_refVal=https%3A%2F%2Fwww.cdc.gov%2Fcoronavirus%2F2019-ncov%2Fprepare%2Fmanaging-stress-anxiety.html", link_text: "Center for Disease Control Guidance on Managing Anxiety and Stress", notes: "These tips may help you cope with your anxiety.", category: "depressed_lonely_anxious", published: true },
      { name: "Tea Time with Sandra", image: "tea_time_with_sandra", about: "A pay-what-you-can online healing circle to help you address everyday oppression with self-compassion - especially during this coronavirus pandemic.", details: "You can attend this gathering every Tuesday and Thursday at 1pm CT. ", link: "https://www.sandrakim.com/tea-time-with-sandra", link_text: "https://www.sandrakim.com/tea-time-with-sandra", notes: "Sandra is very welcoming and offers her services at a pay-what-you-can basis so young people can engage in her services without being at a financial disadvantage!", category: "depressed_lonely_anxious", published: true },
      { name: "TalkSpace", image: "talk_space", about: "An online therapy tool that allows you to connect with a licensed therapist. ", details: "This app allows you to do online counseling via text, audio, and video messaging. There is a cost associated with the service.", link: "https://www.talkspace.com/", link_text: "https://www.talkspace.com/", notes: "They have also made a free public Facebook group and a private Facebook group if you want a space to share and get resources that’s moderated by a therapist. Head over to Facebook and check out the 'Free Public Support Group to Manage Coronavirus Anxiety'", category: "depressed_lonely_anxious", published: true },
      { name: "Dancing Alone Together", image: "dancing_alone_together", about: "A resource for finding online, live-streamed dance classes from jazz to ballet to contemporary fusion.", details: "The website provides links to upcoming live-streamed dance classes from different artists and providers, and on different platforms including Instagram Live and Zoom.", link: "https://www.dancingalonetogether.org/", link_text: "https://www.dancingalonetogether.org/", notes: "You can literally 'dance like no one is watching'!", category: "entertainment_self", published: true },
      { name: "Learn to Cook Something New", image: "learn_to_cook", about: "Find a recipe or instructional video online and create a meal. There are nearly endless options for recipes on YouTube. Some popular cooking channels include: Binging with Babish, Bon Appetit, and Food Wishes.", details: "To do this, you’ll need access to a kitchen and ingredients for whatever you want to make. ", notes: "Learn a new skill and get to eat something delicious. Great way to spend an evening.", category: "entertainment_self", published: true },
      { name: "Memphis Public Library E-collection", image: "mpl_ecollection", about: "Access ebooks and audiobooks for free on your computer, phone, tablet, and reader", details: "Use the Overdrive website or Libby app to check out up to three titles at a time using your library card. (Don’t have a library card? You can get one online instantly!)", link: "http://www.memphislibrary.org/ecollection/start-here-with-the-ecollection/", link_text: "http://www.memphislibrary.org/ecollection/start-here-with-the-ecollection/", notes: "Audiobooks and ebooks instantly downloaded to your device, plus you’re supporting the Memphis Public Library! Win-win.", category: "entertainment_self", published: true },
      { name: "Online Yoga Classes", image: "online_yoga_classes", about: "Even though yoga studios are closed, there are many classes you can access online, some pre-recorded and some live-streaming.", details: "Some popular online yogis post new classes to YouTube regularly, like Yoga with Adriene and Yoga with Kassandra.", notes: "You can combine meditation and movement through yoga.", category: "entertainment_self", published: true },
      { name: "Free Craft Classes", image: "free_creaft_classes", about: "Join in some live or pre-recorded craft classes.", details: "Some sites that you can visit are Class Bento and youtube!", link: "https://classbento.com.au/live-classes-online", link_text: "ClassBento", notes: "This is a great way to release any stress and jumbled thoughts you have.", category: "entertainment_self", published: true },
      { name: "Make a Blog", image: "make_a_blog", about: "A blog is a way to communicate to others around the world that relate to you!", details: "Some web builder sites that you can use for free are Wix, Weebly, Wordpress, Blooger, and Tumblr.", category: "entertainment_self", published: true },
      { name: "Memphis Virtual Events & Experiences", image: "mem_virtual_experiences", about: "A list of ways to stay in and still support & enjoy Memphis that is continually being updated. ", details: "The website provides links to everything from a Print-&-Play escape room, livestream story times, virtual tours and artist talks at your favorite museums, live streams of local bands and trivia nights, exercise classes led by local instructors, and much more!", link: "https://ilovememphisblog.com/2020/04/memphis-social-distancing-virtual-events-and-experiences/", link_text: "https://ilovememphisblog.com/2020/04/memphis-social-distancing-virtual-events-and-experiences/", notes: "If you know of an event or opportunity that you don’t see listed feel free to submit it to the calendar.", category: "entertainment_self", published: true },
      { name: "Bored Button!", image: "bored_button", about: "A fun website with no real purpose", details: "If you’re bored, press the bored button and it will take you to a random minigame. If you’re bored with that minigame press it again to be directed to another minigame!", link: "https://www.boredbutton.com", link_text: "https://www.boredbutton.com", notes: "It’s really easy to waste a lot of time on this site!", category: "entertainment_self", published: true },
      { name: "Vine Compilations", image: "vine_compliations", about: "Funny videos from Vine (RIP) now on Youtube", details: "look up vine compilations on youtube! They’re really funny and there are all kinds of compilations, there’s definitely one you will love!", link: "https://www.youtube.com", link_text: "https://www.youtube.com", category: "entertainment_self", published: true },
      { name: "Calming Apps and Websites to Distract Yourself", image: "calming_apps", about: "Compilations of apps and websites to calm and distract yourself when you are bored or anxious.", details: "look up any of these websites and at least one of them should do the trick", link: "https://www.buzzfeed.com/hannahmarder/20-calming-websites-to-distract-you", link_text: "https://www.buzzfeed.com/hannahmarder/20-calming-websites-to-distract-you", category: "entertainment_self", published: true },
      { name: "Kast", image: "kast", about: "An app for you to play, watch, and be together with your friends and family. A way for you to share your screen to watch a movie, play a game, or to just chat with others.", details: "You can use it to stream any video platform or you can join a public party if you just want to watch the movie with others.", link: "https://kast.gg/", link_text: "https://kast.gg/", notes: "Have some popcorn and get ready to binge your favorite show with your friends!", category: "entertainment_others", published: true },
      { name: "Netflix Party", image: "netflix_party", about: "Netflix Party synchronizes video playback on multiple devices and adds group chat so you and your friends can watch together from your own homes", details: "Only available on Google Chrome browsers for desktop or laptop computers and you must have a Netflix account", link: "https://www.netflixparty.com/", link_text: "https://www.netflixparty.com/", notes: "Have some popcorn and get ready to binge your favorite show with your friends!", category: "entertainment_others", published: true },
      { name: "Online Board and Card Games", image: "online_board_card_games", about: "Just because you can’t leave your house doesn’t mean you can’t still play your favorite games with your friends. A lot of games are available online and as apps. ", details: "Games like Settlers of Catan, Monopoly. Cards Against Humanity, and Classic Card Games like gin rummy and uker can be played together from anywhere.", notes: "If you’re board of binging tv shows, board games are a great way to pass the time with your friends", category: "entertainment_others", published: true },
      { name: "Virtual Book Club", image: "virtual_book_club", about: "You can read a book and talk about it with your friends, all without ever leaving your home. Looking for ideas of books to read? Check below for some ideas. Not sure how to come up with discussion questions? Find some suggestions by checking out Discussion Questions section of BookRiot.com.", details: "Everyone loans a book from the public library or buys it online. Then, you can use a videochat platform like FaceTime or Duo to discuss with friends.", link: "https://www.goodreads.com/list/show/118199.Books_for_Teen_Young_Adult_Discussions", link_text: "https://www.goodreads.com/list/show/118199.Books_for_Teen_Young_Adult_Discussions", notes: "Whether it’s a lighthearted fiction book or a serious memoir, it’s always fun to chat about what you read with someone else", category: "entertainment_others", published: true },
      { name: "Virtual Karaoke Night", image: "virtual_karaoke_night", about: "Using a few different free online services, you can have a karaoke or sing-a-long party without ever leaving your house", details: "Search for karaoke versions of your favorite songs or find a playlist on a YouTube dedicated karaoke channel. Then, using videoconferencing platforms like Zoom or Google Hangouts, share your screen with your friends. ", link: "https://www.youtube.com/user/singkingkaraoke/about", link_text: "https://www.youtube.com/user/singkingkaraoke/about", notes: "Grab your hairbrush and sing into your webcam for a virtual karaoke night with friends!", category: "entertainment_others", published: true },
      { name: "Create a Schedule - Online", image: "create_a_schedule", about: "A key to staying productive while learning at home is maintaining a regular schedule. There are lots of online tools that can help you keep track of your daily and/or weekly schedule and your to-do list!", details: "There are a lot of free options to create and manage your schedule on your phone and computer. Some examples: Google Calendar, Apple Calendar, MyStudyLife", link: "https://zapier.com/blog/best-calendar-apps/#mystudylife", link_text: "https://zapier.com/blog/best-calendar-apps/#mystudylife", notes: "Remember to schedule in downtime for self-care, video games, or however you want to give yourself breaks during the day.", category: "education", published: true },
      { name: "Create a Schedule - On paper", image: "creating_a_schedule_paper", about: "A key to staying productive while learning at home is maintaining a regular schedule. ", details: "There thousands of free templates online that you can use to create your daily and/or weekly schedule and to-do list. Skip To My Lou has some great ones!", link: "https://www.skiptomylou.org/wp-content/uploads/2016/01/weekly_planner_2-1.pdf", link_text: "Template - Weekly Schedule", notes: "Remember to schedule in downtime for self-care, video games, or however you want to give yourself breaks during the day.", category: "education", published: true },
      { name: "Shelby County School Updates and Information", about: "This page provides information and updates regarding school closings, meals for students, etc.", link: "http://www.scsk12.org/coronavirusfacts/", link_text: "http://www.scsk12.org/coronavirusfacts/", category: "education", published: true },
      { name: "Memphis Communiversity", about: "Free ACT tutoring for high school students with St. Mary’s calculus teacher Mason Soun.", details: "Sessions take place from 4 to 6 every Tuesday and Thursday on the Discord app. Practice work is available and questions are encouraged! Email msoun@stmarysschool.org to learn how you can join Memphis Communiversity", link: "https://discord.gg/aeaSARM", link_text: "https://discord.gg/aeaSARM", category: "education", published: true },
      { name: "Khan Academy", about: "Khan Academy is providing daily schedules for students ages 2-18 to keep them learning. Students practice at their own pace, first filling in gaps in their understanding and then accelerating their learning. Courses range from math, science, history, computing, and the arts and humanities. You can also use this for test prep for the SAT and various AP courses.", details: "Need daily learning schedules for students ages 2 - 18? Check out keeplearning.khanacademy.org/daily-schedule", link: "https://www.khanacademy.org/", category: "education", published: true },
      { name: "Additional course resources ", about: "A list of help for classes and additional learning materials to keep your  mind busy during this time", category: "education", published: true }
    ])
  end
end